### PR TITLE
Fix build by removing linker flags

### LINKED ISSUE #294: Linker options causing build failure
This line https://github.com/SteveMacenski/spatio_temporal_voxel_layer/blob/ff95acf46d6b9d15cb3c349dddeaafda5b0425e6/spatio_temporal_voxel_layer/CMakeLists.txt#L13 causes the build to fail when building from scratch.

e.g. Building in Docker on 24.04 ROS Rolling:
```
1137.4 /usr/bin/ld: CMakeFiles/spatio_temporal_voxel_layer_s__rosidl_typesupport_introspection_c.dir/rosidl_generator_py/spatio_temporal_voxel_layer/_spatio_temporal_voxel_layer_s.ep.rosidl_typesupport_introspection_c.c.o: in function `_register_msg_type__srv__save_grid__request':
1137.4 _spatio_temporal_voxel_layer_s.ep.rosidl_typesupport_introspection_c.c:(.text+0x77): undefined reference to `PyCapsule_New'
1137.4 /usr/bin/ld: _spatio_temporal_voxel_layer_s.ep.rosidl_typesupport_introspection_c.c:(.text+0x95): undefined reference to `PyModule_AddObject'                                        
1137.4 /usr/bin/ld: _spatio_temporal_voxel_layer_s.ep.rosidl_typesupport_introspection_c.c:(.text+0xb0): undefined reference to `PyCapsule_New'                                             
1137.4 /usr/bin/ld: _spatio_temporal_voxel_layer_s.ep.rosidl_typesupport_introspection_c.c:(.text+0xce): undefined reference to `PyModule_AddObject'                                        
1137.4 /usr/bin/ld: _spatio_temporal_voxel_layer_s.ep.rosidl_typesupport_introspection_c.c:(.text+0xe9): undefined reference to `PyCapsule_New'                                             
1137.4 /usr/bin/ld: _spatio_temporal_voxel_layer_s.ep.rosidl_typesupport_introspection_c.c:(.text+0x107): undefined reference to `PyModule_AddObject'                                       
1137.4 /usr/bin/ld: _spatio_temporal_voxel_layer_s.ep.rosidl_typesupport_introspection_c.c:(.text+0x11e): undefined reference to `PyCapsule_New'                                            
1137.4 /usr/bin/ld: _spatio_temporal_voxel_layer_s.ep.rosidl_typesupport_introspection_c.c:(.text+0x138): undefined reference to `PyModule_AddObject'                                       
1137.4 /usr/bin/ld: _spatio_temporal_voxel_layer_s.ep.rosidl_typesupport_introspection_c.c:(.text+0x150): undefined reference to `PyCapsule_New'                                            
1137.4 /usr/bin/ld: _spatio_temporal_voxel_layer_s.ep.rosidl_typesupport_introspection_c.c:(.text+0x16a): undefined reference to `PyModule_AddObject'
1137.4 /usr/bin/ld: _spatio_temporal_voxel_layer_s.ep.rosidl_typesupport_introspection_c.c:(.text+0x196): undefined reference to `_Py_Dealloc'
```

I suspect this line was added when splitting out VDB to help with development.

If I build without these linker flags, then re-add the flags and rebuild it works. So I suspect that the order in which things are being built is the problem, which goes away once the previous versions of the libraries exist in the workspace.

### PR DESCRIPTION
**Pull request by james-ward**
Closes #294

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]
Waiting on @Timple but LGTM.

**Comment by Timple** [comment]
Well, this check should not have false positives. But you are right, there is an issue upstream which causes this: https://github.com/ros2/rosidl_python/issues/213 

I would put these lines below the message generation, that also works. With a comment why this is at that location referencing the upstream issue.

But I'm also not against removing it as it's just an extra check preventing runtime linking issues.

**Comment by SteveMacenski** [comment]
That seems reasonable to me. @james-ward can you move it below the messages?

**Review by SteveMacenski — APPROVED** [review]

**Comment by Rayman** [comment]
~~@james-ward you can also move the linker flags *after* the messages are generated. Then we still get warnings from our own code, but not from the messages~~

**Pull request merged**
